"""expand document metadata

Revision ID: 6889e3cad269
Revises: 0c793a7c686f
Create Date: 2026-07-16 18:27:11.536229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6889e3cad269'
down_revision: Union[str, Sequence[str], None] = '0c793a7c686f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('s3_key', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 's3_key')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
